### Get Post for current user
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikt5bGUiLCJyb2xlIjoiVXNlciIsImlhdCI6MTYzNDgxOTY1MCwiZXhwIjoxNjM0ODE5NjgwfQ.H8GEBZtoZ5w6T0-XXRgEYZfFjX6MNSV5KgbiX3ERSu8



### Get all posts for all users (Admin only)
GET http://localhost:3000/all-posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikt5bGUiLCJyb2xlIjoiVXNlciIsImlhdCI6MTYzNDgxOTY1MCwiZXhwIjoxNjM0ODE5NjgwfQ.H8GEBZtoZ5w6T0-XXRgEYZfFjX6MNSV5KgbiX3ERSu8



### Remove refresh token in db
DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkppbSIsImlhdCI6MTYzNDgxNzE2MH0.tkMpT6QQjlpDmeypUuZDYlj3jOVBlB_4yN0ear0hFbg"
}


### Get new access token based on refresh token
POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjM0ODE5NjIzfQ.EPDYjARxikMDyelVRh19dxzABsJdUYdl9I0bKyZLXt0"
}


### Login 1
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Admin",
  "password": "admin123"
}


### Login 2
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Kyle",
  "password": "kyle123"
}


### Register 1
POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "Admin",
  "password": "admin123",
  "role": "Admin"
}


### Register 2
POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "Kyle",
  "password": "kyle123",
  "role": "User"
}


### Get users
GET http://localhost:4000/users


### Get refreshTokens
GET http://localhost:4000/refresh_tokens