### 1. Get Post for current user (access token)
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjM1NzU1MDUxLCJleHAiOjE2MzU3NTUwODF9.l-TtDWuHt3ItTNC9IvRFwZuTPNdv464x2iGNDIQYd3M




### 2. Get all posts for all users (Admin only)
GET http://localhost:3000/all-posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjM1NzU1MDUxLCJleHAiOjE2MzU3NTUwODF9.l-TtDWuHt3ItTNC9IvRFwZuTPNdv464x2iGNDIQYd3M




### 3. Remove refresh token in db
DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIiLCJyb2xlIjoiVXNlciIsImlhdCI6MTYzNTc1NDM3MX0.vt9ZKDacyaIFK7JlAMMveWF10TWDHgoZzo5qp1mxZ9g"
  }


### 4. Get new access token based on refresh token
POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIiLCJyb2xlIjoiVXNlciIsImlhdCI6MTYzNTc1NDk3MX0.1bQ93A80V2bgzaWvp77IBD1A5jzZqdPFObz8FNs0dTc"
}


### 5. Login 1 (Admin)
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Admin",
  "password": "admin123"
}


### 6. Login 2 (User)
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "User",
  "password": "user123"
}


### 7. Register 1 (Admin)
POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "Admin",
  "password": "admin123",
  "role": "Admin"
}


### 8. Register 2 (User)
POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "User",
  "password": "user123",
  "role": "User"
}

### Helper requests
### 9. Get users
GET http://localhost:4000/users


### 10. Get refreshTokens
GET http://localhost:4000/refresh_tokens